<?php
/**
 * Backup photos, shown only when a slot's main photo (Admin → Photos) can't load,
 * for example without internet. From Google's Open Images collection
 * (https://storage.googleapis.com/openimages/web/index.html), CC BY 2.0;
 * the photographers are credited on the Photo credits page.
 */

return [
    'cyber' => ['file' => 'img/fallback/c565b2690c3af6a7.jpg', 'alt' => 'Two colleagues concentrating on their laptops', 'w' => 1024, 'h' => 768, 'author' => 'Matt', 'title' => 'Geophysics Hackathon', 'source' => 'https://www.flickr.com/photos/kwinkunks/9890061173', 'license' => 'CC BY 2.0', 'license_url' => 'https://creativecommons.org/licenses/by/2.0/'],
    'webdev' => ['file' => 'img/fallback/9b010d0128f888e7.jpg', 'alt' => 'Team working together on laptops around a long table', 'w' => 1024, 'h' => 683, 'author' => 'Théo Chevalier', 'title' => 'IMG_0164', 'source' => 'https://www.flickr.com/photos/79614402@N07/7359727194', 'license' => 'CC BY 2.0', 'license_url' => 'https://creativecommons.org/licenses/by/2.0/'],
    'itsupport' => ['file' => 'img/fallback/9b2773fe0f808238.jpg', 'alt' => 'Man working on a laptop at a desk', 'w' => 1024, 'h' => 1024, 'author' => 'David Sifry', 'title' => 'Hm, what happens if I push this?', 'source' => 'https://www.flickr.com/photos/dsifry/2773358945', 'license' => 'CC BY 2.0', 'license_url' => 'https://creativecommons.org/licenses/by/2.0/'],
    'training' => ['file' => 'img/fallback/e18f8379d3e272b5.jpg', 'alt' => 'Trainer leading a workshop for adults with laptops', 'w' => 1024, 'h' => 743, 'author' => 'Eva Blue', 'title' => 'spice corps montreal 2', 'source' => 'https://www.flickr.com/photos/evablue/5738800135', 'license' => 'CC BY 2.0', 'license_url' => 'https://creativecommons.org/licenses/by/2.0/'],
    'cloud' => ['file' => 'img/fallback/72015d23bbdb911a.jpg', 'alt' => 'Computer room with people working at their desks', 'w' => 1024, 'h' => 768, 'author' => 'Ewout ter Haar', 'title' => 'Sala de aula', 'source' => 'https://www.flickr.com/photos/ewout/2821470868', 'license' => 'CC BY 2.0', 'license_url' => 'https://creativecommons.org/licenses/by/2.0/'],
    'consulting' => ['file' => 'img/fallback/ee4a6992245df8ff.jpg', 'alt' => 'Facilitators leading a planning session with a flip chart', 'w' => 1024, 'h' => 701, 'author' => 'South Carolina Hospital Association', 'title' => 'DSC_2221', 'source' => 'https://www.flickr.com/photos/schospitals/16288938765', 'license' => 'CC BY 2.0', 'license_url' => 'https://creativecommons.org/licenses/by/2.0/'],
    'team' => ['file' => 'img/fallback/1eb99df4147f898f.jpg', 'alt' => 'Three colleagues talking in a meeting room', 'w' => 1024, 'h' => 768, 'author' => 'Michael Coté', 'title' => 'Serial Solutions Austin', 'source' => 'https://www.flickr.com/photos/cote/4515587634/', 'license' => 'CC BY 2.0', 'license_url' => 'https://creativecommons.org/licenses/by/2.0/'],
    'services' => ['file' => 'img/fallback/a52e6c946be1524b.jpg', 'alt' => 'People working on laptops in a training room', 'w' => 1024, 'h' => 575, 'author' => 'Stephan Ridgway', 'title' => 'Online Webinar', 'source' => 'https://www.flickr.com/photos/stephanridgway/5166666608', 'license' => 'CC BY 2.0', 'license_url' => 'https://creativecommons.org/licenses/by/2.0/'],
    'people' => ['file' => 'img/fallback/1e471949af0ac2f5.jpg', 'alt' => 'Three colleagues working together on a laptop', 'w' => 1024, 'h' => 683, 'author' => 'corinnepw', 'title' => 'LadyHacks 2014', 'source' => 'https://www.flickr.com/photos/oh_you/13042451783', 'license' => 'CC BY 2.0', 'license_url' => 'https://creativecommons.org/licenses/by/2.0/'],
    'about' => ['file' => 'img/fallback/9e2c53451ec7bbc0.jpg', 'alt' => 'Workshop participants with laptops listening to a talk', 'w' => 1024, 'h' => 683, 'author' => 'Centre for E-Government Danube University Krems', 'title' => 'IMG_8716', 'source' => 'https://www.flickr.com/photos/e-governance/11121818035', 'license' => 'CC BY 2.0', 'license_url' => 'https://creativecommons.org/licenses/by/2.0/'],
    'blog' => ['file' => 'img/fallback/2bb198e99eb2b8ba.jpg', 'alt' => 'People taking notes and working on laptops at a workshop', 'w' => 1024, 'h' => 768, 'author' => 'mihi_tr', 'title' => 'PB100742.JPG', 'source' => 'https://www.flickr.com/photos/mihi_tr/8244747706', 'license' => 'CC BY 2.0', 'license_url' => 'https://creativecommons.org/licenses/by/2.0/'],
    'resources' => ['file' => 'img/fallback/72015d23bbdb911a.jpg', 'alt' => 'Computer room with people working at their desks', 'w' => 1024, 'h' => 768, 'author' => 'Ewout ter Haar', 'title' => 'Sala de aula', 'source' => 'https://www.flickr.com/photos/ewout/2821470868', 'license' => 'CC BY 2.0', 'license_url' => 'https://creativecommons.org/licenses/by/2.0/'],
    'post-mfa' => ['file' => 'img/fallback/7d492bdddcde164e.jpg', 'alt' => 'Hand holding a smartphone', 'w' => 1024, 'h' => 768, 'author' => 'Bernard Goldbach', 'title' => 'iPhone and #Tipp-MC', 'source' => 'https://www.flickr.com/photos/topgold/4993741649', 'license' => 'CC BY 2.0', 'license_url' => 'https://creativecommons.org/licenses/by/2.0/'],
    'post-phishing' => ['file' => 'img/fallback/4dc6f35409b2df20.jpg', 'alt' => 'Two people typing on laptops, seen from above', 'w' => 1024, 'h' => 576, 'author' => 'Ankarino', 'title' => 'IMG_0290', 'source' => 'https://www.flickr.com/photos/ankarino/2712455020', 'license' => 'CC BY 2.0', 'license_url' => 'https://creativecommons.org/licenses/by/2.0/'],
    'post-website' => ['file' => 'img/fallback/1e471949af0ac2f5.jpg', 'alt' => 'Three colleagues working together on a laptop', 'w' => 1024, 'h' => 683, 'author' => 'corinnepw', 'title' => 'LadyHacks 2014', 'source' => 'https://www.flickr.com/photos/oh_you/13042451783', 'license' => 'CC BY 2.0', 'license_url' => 'https://creativecommons.org/licenses/by/2.0/'],
    'post-backup' => ['file' => 'img/fallback/9b010d0128f888e7.jpg', 'alt' => 'Team working together on laptops around a long table', 'w' => 1024, 'h' => 683, 'author' => 'Théo Chevalier', 'title' => 'IMG_0164', 'source' => 'https://www.flickr.com/photos/79614402@N07/7359727194', 'license' => 'CC BY 2.0', 'license_url' => 'https://creativecommons.org/licenses/by/2.0/'],
];
